export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const OAUTH_REQUEST = "OAUTH_REQUEST";
export const OAUTH_SUCCESS = "OAUTH_SUCCESS";
export const OAUTH_ERROR = "OAUTH_ERROR";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_UPDATE_REQUEST = "LOGIN_UPDATE_REQUEST";
export const LOGIN_UPDATE_SUCCESS = "LOGIN_UPDATE_SUCCESS";
export const LOGIN_UPDATE_ERROR = "LOGIN_UPDATE_ERROR";
export const PASSWORD_CREATE_REQUEST = "PASSWORD_CREATE_REQUEST";
export const PASSWORD_CREATE_SUCCESS = "PASSWORD_CREATE_SUCCESS";
export const PASSWORD_CREATE_ERROR = "PASSWORD_CREATE_ERROR";

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";

export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";

export const GOTO = "GOTO";

export const COACH_FETCH_REQUEST = "COACH_FETCH_REQUEST";
export const COACH_FETCH_SUCCESS = "COACH_FETCH_SUCCESS";
export const COACH_FETCH_ERROR = "COACH_FETCH_ERROR";

export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR";
export const PRODUCT_DESTROY_REQUEST = "PRODUCT_DESTROY_REQUEST";
export const PRODUCT_DESTROY_SUCCESS = "PRODUCT_DESTROY_SUCCESS";
export const PRODUCT_DESTROY_ERROR = "PRODUCT_DESTROY_ERROR";
export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR";
export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const CLIENT_TOKEN_REQUEST = "CLIENT_TOKEN_REQUEST";
export const CLIENT_TOKEN_SUCCESS = "CLIENT_TOKEN_SUCCESS";
export const CLIENT_TOKEN_ERROR = "CLIENT_TOKEN_ERROR";
export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_ERROR = "TRANSACTION_CREATE_ERROR";
export const TRANSACTION_FETCH_REQUEST = "TRANSACTION_FETCH_REQUEST";
export const TRANSACTION_FETCH_SUCCESS = "TRANSACTION_FETCH_SUCCESS";
export const TRANSACTION_FETCH_ERROR = "TRANSACTION_FETCH_ERROR";
