export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_RESPONSE = "LOGOUT_RESPONSE";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const OAUTH_REQUEST = "OAUTH_REQUEST";
export const OAUTH_RESPONSE = "OAUTH_RESPONSE";
export const OAUTH_ERROR = "OAUTH_ERROR";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_UPDATE_REQUEST = "LOGIN_UPDATE_REQUEST";
export const LOGIN_UPDATE_RESPONSE = "LOGIN_UPDATE_RESPONSE";
export const LOGIN_UPDATE_ERROR = "LOGIN_UPDATE_ERROR";
export const PASSWORD_CREATE_REQUEST = "PASSWORD_CREATE_REQUEST";
export const PASSWORD_CREATE_RESPONSE = "PASSWORD_CREATE_RESPONSE";
export const PASSWORD_CREATE_ERROR = "PASSWORD_CREATE_ERROR";

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";

export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";

export const ROUTE_CHANGE = "ROUTE_CHANGE";

export const COACH_FETCH_REQUEST = "COACH_FETCH_REQUEST";
export const COACH_FETCH_RESPONSE = "COACH_FETCH_RESPONSE";
export const COACH_FETCH_ERROR = "COACH_FETCH_ERROR";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_RESPONSE = "PRODUCT_CREATE_RESPONSE";
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR";
export const PRODUCT_DESTROY_REQUEST = "PRODUCT_DESTROY_REQUEST";
export const PRODUCT_DESTROY_RESPONSE = "PRODUCT_DESTROY_RESPONSE";
export const PRODUCT_DESTROY_ERROR = "PRODUCT_DESTROY_ERROR";
export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_RESPONSE = "PRODUCT_FETCH_RESPONSE";
export const PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR";
export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_RESPONSE = "PRODUCT_UPDATE_RESPONSE";
export const PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_RESPONSE = "USER_CREATE_RESPONSE";
export const USER_CREATE_ERROR = "USER_CREATE_ERROR";
export const USER_DESTROY_REQUEST = "USER_DESTROY_REQUEST";
export const USER_DESTROY_RESPONSE = "USER_DESTROY_RESPONSE";
export const USER_DESTROY_ERROR = "USER_DESTROY_ERROR";
export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_RESPONSE = "USER_FETCH_RESPONSE";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_RESPONSE = "USER_UPDATE_RESPONSE";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const CLIENT_TOKEN_REQUEST = "CLIENT_TOKEN_REQUEST";
export const CLIENT_TOKEN_RESPONSE = "CLIENT_TOKEN_RESPONSE";
export const CLIENT_TOKEN_ERROR = "CLIENT_TOKEN_ERROR";
export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_RESPONSE = "TRANSACTION_CREATE_RESPONSE";
export const TRANSACTION_CREATE_ERROR = "TRANSACTION_CREATE_ERROR";
export const TRANSACTION_FETCH_REQUEST = "TRANSACTION_FETCH_REQUEST";
export const TRANSACTION_FETCH_RESPONSE = "TRANSACTION_FETCH_RESPONSE";
export const TRANSACTION_FETCH_ERROR = "TRANSACTION_FETCH_ERROR";
